const product = [
    {
        id: 0,
        name: "HP ZBook Firefly 15 G7 Mobile Workstation",
        colour: "Silver",
        O_Price: 6556.00,
        D_Price: 6056.00,
        A_Saved: 500.00,
        image_src: "../product/zbook/1.png",
        href: "P1.html",
    },
    {
        id: 1,
        name: "Lenovo Legion 7i",
        colour: "Black",
        O_Price: 10699.00,
        D_Price: 9699.00,
        A_Saved: 1000.00,
        image_src: "../product/Legion/1.png",
        href: "P2.html",
    },
    {
    id: 3,
        name: "MSI WS75 Mobile Workstation",
        colour: "Silver",
        O_Price: 16399.00,
        D_Price: 0.00,
        A_Saved: 0.00,
        image_src: "../product/MSI/1.png",
        href: "P3.html",
    },
    {
        id: 4,
        name: "ASUS ROG Zephyrus G15",
        colour: "Black",
        O_Price: 5299.00,
        D_Price: 5099.00,
        A_Saved: 200.00,
        image_src: "../product/Zephyrus/1.png",
        href: "P4.html",
    },
    {
        id: 5,
        name: "Macbook Pro",
        colour: "Space Grey",
        O_Price: 6399.00,
        D_Price: 0.00,
        A_Saved: 0.00,
        image_src: "../product/MacbookPro/1.png",
        href: "P5.html",
    },
    {
        id: 6,
        name: "Macbook Air",
        colour: "Rose Gold",
        O_Price: 4399.00,
        D_Price: 0.00,
        A_Saved: 0.00,
        image_src: "../product/MacbookAir/1.png",
        href: "P6.html",
    },
    {
        id: 7,
        name: "Huawei MateBook 14",
        colour: "Silver",
        O_Price: 3799.00,
        D_Price: 0.00,
        A_Saved: 0.00,
        image_src: "../product/Huawei/1.png",
        href: "P7.html",
    },
    {
        id: 8,
        name: "Dell Inspiron 15 Plus",
        colour: "White",
        O_Price: 5199.00,
        D_Price: 0.00,
        A_Saved: 0.00,
        image_src: "../product/Dell/1.png",
        href: "P8.html",
    },
    {
        id: 9,
        name: "MSI GF63 Thin 10UC 644",
        colour: "White",
        O_Price: 3949.00,
        D_Price: 0.00,
        A_Saved: 0.00,
        image_src: "../product/MSIGF/1.png",
        href: "P9.html",
    },
]